# PyTorch Freecodecamp Tutorial

In [ ]:
print("About to learn PyTorch")

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

## Introduction to Tensors

### Creating Tensors

Pytorch tensors are created using torch.tensor ot torch.Tensor

In [ ]:
scalar = torch.tensor(7)
print(scalar)

print(scalar.ndim)
print(scalar.shape)

# Get tensor back as python int
print(scalar.item())

In [ ]:
# Vector
vector  = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape)

In [ ]:
MATRIX = torch.tensor([[7, 9],[9, 10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[1])

In [ ]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0])

### Random Tensors

Why tensors?
Random tensors are important because the way the neural networks learn is  that tthey  start with tensors  full of random numbers  and then adjust those numbers to better represent the data

In [ ]:
# Create a tensor of a random size
random_tensor = torch.rand(3,4)
print(random_tensor)

In [ ]:
random_image_size_tensor = torch.rand(size=(224,224,3))
print(random_image_size_tensor.shape, random_image_size_tensor.ndim)

### Zeroes and Ones

In [ ]:
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
# print(zeros)
# print(ones)

### Range and Like

In [ ]:
one_to_ten = torch.arange(start=1,end=11,step=1)
print(one_to_ten)

zeros_like = torch.zeros_like(one_to_ten)
print(zeros_like)

### Tensor datatypes

**Note** : Tensor datatypes is one of the 3 big errors  you'll run into iin PyTorch and deep learning
1. Not right data type
2. Not right shape
3. Not right device

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],dtype=None,device=None,requires_grad=False)

float_16_tensor = float_32_tensor.type(torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int64)
int_32_tensor = torch.tensor([3,6,9], dtype=torch.float16)
int_32_tensor = torch.tensor([3,6,9], dtype=torch.float32)
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)

### Print details

Helpful in troubleshooting problems

In [ ]:
some_tensor = torch.rand(3,4)
print(some_tensor)
print(f"Data type : {some_tensor.dtype}")
print(f"Shape : {some_tensor.shape}")
print(f"Size : {some_tensor.size()}")
print(f"Data type : {some_tensor.device}")

### Manipulating Tensors (tensor operations)

Tensor operations include 
- Addition
- Subtraction
- Multiplication
- Division
- Matrix Multiplication

In [120]:
# Create a tensor

tensor1 = torch.tensor([1,2,3])
print(tensor1 + 10)
print(tensor1 * 10)
print(tensor1 / 10)

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])
