# PyTorch Freecodecamp Tutorial

In [37]:
print("About to learn PyTorch")

About to learn PyTorch


In [38]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [39]:
print(torch.__version__)

2.0.1+cu117


## Introduction to Tensors

### Creating Tensors

Pytorch tensors are created using torch.tensor ot torch.Tensor

In [40]:
scalar = torch.tensor(7)
print(scalar)

print(scalar.ndim)
print(scalar.shape)

# Get tensor back as python int
print(scalar.item())

tensor(7)
0
torch.Size([])
7


In [41]:
# Vector
vector  = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [42]:
MATRIX = torch.tensor([[7, 9],[9, 10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[1])

tensor([[ 7,  9],
        [ 9, 10]])
2
torch.Size([2, 2])
tensor([ 9, 10])


In [43]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


### Random Tensors

Why tensors?
Random tensors are important because the way the neural networks learn is  that tthey  start with tensors  full of random numbers  and then adjust those numbers to better represent the data

In [45]:
# Create a tensor of a random size
random_tensor = torch.rand(3,4)
print(random_tensor)

tensor([[0.5671, 0.9295, 0.5933, 0.4060],
        [0.7331, 0.0607, 0.9520, 0.0208],
        [0.3398, 0.7296, 0.5877, 0.0231]])


In [47]:
random_image_size_tensor = torch.rand(size=(224,224,3))
print(random_image_size_tensor.shape, random_image_size_tensor.ndim)

torch.Size([224, 224, 3]) 3


### Zeroes and Ones

In [51]:
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
# print(zeros)
# print(ones)

### Range

In [ ]:
one_to_ten = torch.arange(start=1,)