# PyTorch Freecodecamp Tutorial

In [1]:
print("About to learn PyTorch")

About to learn PyTorch


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
print(torch.__version__)

2.1.1+cu121


## Introduction to Tensors

### Creating Tensors

Pytorch tensors are created using torch.tensor ot torch.Tensor

In [4]:
scalar = torch.tensor(7)
print(scalar)

print(scalar.ndim)
print(scalar.shape)

# Get tensor back as python int
print(scalar.item())

tensor(7)
0
torch.Size([])
7


In [5]:
# Vector
vector  = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [6]:
MATRIX = torch.tensor([[7, 9],[9, 10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)
print(MATRIX[1])

tensor([[ 7,  9],
        [ 9, 10]])
2
torch.Size([2, 2])
tensor([ 9, 10])


In [7]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


### Random Tensors

Why tensors?
Random tensors are important because the way the neural networks learn is  that tthey  start with tensors  full of random numbers  and then adjust those numbers to better represent the data

In [8]:
# Create a tensor of a random size
random_tensor = torch.rand(3,4)
print(random_tensor)

tensor([[0.6741, 0.7558, 0.6407, 0.5304],
        [0.0339, 0.1569, 0.7782, 0.9649],
        [0.4875, 0.5413, 0.0156, 0.1195]])


In [9]:
random_image_size_tensor = torch.rand(size=(224,224,3))
print(random_image_size_tensor.shape, random_image_size_tensor.ndim)

torch.Size([224, 224, 3]) 3


### Zeroes and Ones

In [10]:
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
# print(zeros)
# print(ones)

### Range and Like

In [11]:
one_to_ten = torch.arange(start=1,end=11,step=1)
print(one_to_ten)

zeros_like = torch.zeros_like(one_to_ten)
print(zeros_like)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensor datatypes

**Note** : Tensor datatypes is one of the 3 big errors  you'll run into iin PyTorch and deep learning
1. Not right data type
2. Not right shape
3. Not right device

In [12]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],dtype=None,device=None,requires_grad=False)

float_16_tensor = float_32_tensor.type(torch.float16)

In [13]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int64)
int_32_tensor = torch.tensor([3,6,9], dtype=torch.float16)
int_32_tensor = torch.tensor([3,6,9], dtype=torch.float32)
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)

### Print details

Helpful in troubleshooting problems

In [14]:
some_tensor = torch.rand(3,4)
print(some_tensor)
print(f"Data type : {some_tensor.dtype}")
print(f"Shape : {some_tensor.shape}")
print(f"Size : {some_tensor.size()}")
print(f"Data type : {some_tensor.device}")

tensor([[0.7488, 0.0742, 0.7331, 0.3580],
        [0.1012, 0.7960, 0.2565, 0.9711],
        [0.2070, 0.7315, 0.4923, 0.5581]])
Data type : torch.float32
Shape : torch.Size([3, 4])
Size : torch.Size([3, 4])
Data type : cpu


### Manipulating Tensors (tensor operations)

Tensor operations include 
- Addition
- Subtraction
- Multiplication
- Division
- Matrix Multiplication

In [15]:
# Create a tensor

tensor1 = torch.tensor([1,2,3])
print(tensor1 + 10)
print(tensor1 * 10)
print(tensor1 / 10)

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [16]:
# Multiplication can be of two types :-
# Element wise

tensor2 = torch.tensor([1,2,3])
print(tensor2*tensor2)

# Matrix multiplication (dot product)
print(torch.matmul(tensor2,tensor2))

tensor([1, 4, 9])
tensor(14)


In [17]:
# Use built-in functions as they are more efficient 

# Two conditions for matrix multiplication
1. The inner dimensions must match
(3,2) * (3,2) won't work
(3,2) * (2,3) will work

Note :
In pytorch , we use torch.mm or torch.matmul for both matrix multiplication and dot product
the idea being if the tensors are 1-D then the result will be a dot product
else the result be standard matrix multiplication

In [18]:
# Transpose 
# transpose helps fix dimension/shape errors
# transpose switches the axes/dimensions of a vector

tensorB = torch.tensor([[1,2,4],[3,1,2]])

print("Original Tensor : ")
print(tensorB)
print("Transpose ")
print(tensorB.T)

print("Matrix multiplication ")
print(torch.matmul(tensorB, tensorB.T))

# You could also do 
print(torch.mm(tensorB,tensorB.T))

Original Tensor : 
tensor([[1, 2, 4],
        [3, 1, 2]])
Transpose 
tensor([[1, 3],
        [2, 1],
        [4, 2]])
Matrix multiplication 
tensor([[21, 13],
        [13, 14]])
tensor([[21, 13],
        [13, 14]])


# Aggregate functions

min,max,mean,sum

Note : torch.mean cannot work with int64, int32 data types
it cal work with float32 data types

In [19]:
# Create a tensor
x = torch.arange(0,100,10)
print(x, x.dtype)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]) torch.int64


In [20]:
print("Min : ")
print(torch.min(x))
print(x.min())

print("Max : ")
print(torch.max(x))
print(x.max())

print("Sum : ")
print(torch.sum(x))
print(x.sum())


print("Mean : ")
# Following does not work 
# You must explicitly type cast it
# print(torch.mean(x))

print(torch.mean(x.type(torch.float32)))
print(x.type(torch.float32).mean())

Min : 
tensor(0)
tensor(0)
Max : 
tensor(90)
tensor(90)
Sum : 
tensor(450)
tensor(450)
Mean : 
tensor(45.)
tensor(45.)


# Positional Max , Min

#### Argmax -> Index of the max element
#### Argmin -> Index of the min element


In [21]:
print("Argmax : ")
print(torch.argmax(x))
print(x.argmax())

print("Argmin : ")
print(torch.argmin(x))
print(x.argmin())

Argmax : 
tensor(9)
tensor(9)
Argmin : 
tensor(0)
tensor(0)


# Reshaping, Stacking, Squeezing, , Unsqueezing tensors


reshaping - reshapes an input tensor to a defined shape  
stacking - combining multiple tensors on top of each other (vstack) or side by side (hstack)  
squeeze - remove `1` dimensions from a vector  
unsqueeze - add `1` dimensions to a vector  
permute - return the view of the input dimensions permuted (swapped) in a certain way


In [22]:
# Create a tensor 
x = torch.arange(1.,10.)
# we used 1. and 10. instead of 1 and 10 to use float32 data type
print(x, x.shape, x.dtype)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9]) torch.float32


In [23]:
# GPU Testing

# https://stackabuse.com/how-to-use-gpus-with-pytorch/
print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.current_device())


True
1
0
